config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :deposits, only: [:new, :create]
  resources :withdraws, only: [:new, :create]
  resources :transfers, only: [:new, :create]

  root "users#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deposit.rb
# frozen_string_literal: true

class Deposit < Transaction
  validates :target_id, presence: true
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :source, class_name: 'Wallet', optional: true
  belongs_to :target, class_name: 'Wallet', optional: true
  belongs_to :user

  validates :total, presence: true
  validates :total, numericality: { greater_than: 0 }

  def self.create_transaction(params)
    transaction do
      depo = new(params)
      depo.save
      depo.update_wallet

      depo
    end
  end

  def update_wallet
    case self
    when Deposit
      wallet_ids = [target_id]
    when Withdraw
      wallet_ids = [source_id]
    when Transfer
      wallet_ids = [target_id, source_id]
    end

    return unless wallet_ids.present?

    Wallet.where(id: wallet_ids).each(&:calculation_total)
  end

  def check_ownership_and_total
    wallet_total = Wallet.select('total, user_id').find_by(id: source_id)
    if wallet_total.present? && total.to_f > wallet_total&.total.to_f
      errors.add(:total, "can't be greater than balance")
    end

    errors.add(:source, 'is not yours') unless wallet_total.user_id == user_id
  end
end

app/models/transfer.rb
# frozen_string_literal: true

class Transfer < Transaction
  validates :target_id, :source_id, presence: true

  validate :check_ownership_and_total
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one :wallet
end

app/models/wallet.rb
# frozen_string_literal: true

class Wallet < ApplicationRecord
  def calculation_total
    transaction do
      deposit_total = Deposit.where(target_id: id).sum(:total)
      wd_total = Withdraw.where(source_id: id).sum(:total)

      # transfer in
      transfer_in = Transfer.where(target_id: id).sum(:total)

      # transfer out
      transfer_out = Transfer.where(source_id: id).sum(:total)

      update(total: (deposit_total - wd_total) + (transfer_in - transfer_out))
    end
  end
end

app/models/withdraw.rb
# frozen_string_literal: true

class Withdraw < Transaction
  validates :source_id, presence: true

  validate :check_ownership_and_total
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/deposits_controller.rb
# frozen_string_literal: true

class DepositsController < ApplicationController
  before_action :check_target_wallet, only: :new

  def new
    @deposit = Deposit.new
    @user = User.first
    @deposit.user = @user
  end

  def create
    @deposit = Deposit.new permit_params

    if @deposit.valid?
      Deposit.create_transaction permit_params
      redirect_to root_path,
                  notice: "Deposit to wallet : #{@deposit.target.name} success"
    else
      @target_wallet = @deposit.target
      flash.now[:alert] = "Deposit to wallet #{@deposit.target.name} failed"
      render :new
    end
  end

  protected

    def permit_params
      params.require(:deposit).permit(:user_id, :target_id, :total)
    end

    def check_target_wallet
      @target_wallet = Wallet.find_by(id: params[:target_id])

      return if @target_wallet.present?

      redirect_to root_path, notice: 'Target wallet not found'
    end
end

app/controllers/transfers_controller.rb
# frozen_string_literal: true

class TransfersController < ApplicationController
  before_action :prepulate_data
  before_action :check_source_wallet, only: :new

  def new
    @tf = Transfer.new
    @user = User.first
    @tf.user = @user
  end

  def create
    @tf = Transfer.new permit_params

    if @tf.valid?
      Transfer.create_transaction permit_params
      redirect_to root_path,
                  notice: "Withdraw to wallet : #{@tf.source.name} success"
    else
      @source_wallet = @tf.source
      @wallets = @wallets.where.not(id: @source_wallet)
      flash.now[:alert] = "Withdraw to wallet #{@tf.source.name} failed"
      render :new
    end
  end

  protected

    def permit_params
      params.require(:transfer).permit(:user_id, :source_id, :target_id, :total)
    end

    def check_source_wallet
      @source_wallet = Wallet.find_by(id: params[:source_id])

      return if @source_wallet.present?

      redirect_to root_path, notice: 'Source wallet not found'
    end

    def prepulate_data
      @wallets = Wallet.select('id,name').where.not(id: params[:source_id])
    end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.includes(:wallet).all
  end
end

app/controllers/withdraws_controller.rb
# frozen_string_literal: true

class WithdrawsController < ApplicationController
  before_action :check_source_wallet, only: :new

  def new
    @wd = Withdraw.new
    @user = User.first
    @wd.user = @user
  end

  def create
    @wd = Withdraw.new permit_params

    if @wd.valid?
      Withdraw.create_transaction permit_params
      redirect_to root_path,
                  notice: "Withdraw to wallet : #{@wd.source.name} success"
    else
      @source_wallet = @wd.source
      flash.now[:alert] = "Withdraw to wallet #{@wd.source.name} failed"
      render :new
    end
  end

  protected

    def permit_params
      params.require(:withdraw).permit(:user_id, :source_id, :total)
    end

    def check_source_wallet
      @source_wallet = Wallet.find_by(id: params[:source_id])

      return if @source_wallet.present?

      redirect_to root_path, notice: 'Source wallet not found'
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/deposits_helper.rb
# frozen_string_literal: true

module DepositsHelper
end

app/helpers/transfers_helper.rb
# frozen_string_literal: true

module TransfersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/withdraws_helper.rb
# frozen_string_literal: true

module WithdrawsHelper
end

app/views/deposits/new.html.erb
<style>
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
</style>

<main class="form-signin">
  <% flash.each do |type, msg| %>
  <div class="alert alert-primary" role="alert">
      <%= msg %>
  </div>
  <% end %>
  <% @deposit.errors.full_messages.each do |x| %>
  <div class="alert alert-secondary" role="alert">
    <%= x %>
  </div>
  <% end %>
  <%= form_with model: @deposit do |form| %>
    <h1 class="h3 mb-3 fw-normal">Deposit</h1>
    </br>
    <h2>Send to Wallet: <%= @target_wallet&.name %></h2>
  
    <div class="form-floating">
      <%= form.hidden_field(:user_id) %>
      <%= form.hidden_field(:target_id, { value: @deposit.target&.id || params[:target_id] }) %>
      <%= form.text_field(:total, { class: 'form-control', value: @deposit.total || '10.0'}) %>
      <%= form.label(:total, "Total :") %>
    </div>

    </br>
    <%= submit_tag('Send Deposit', { class: "w-100 btn btn-lg btn-primary" }) %>
    <%= link_to('Cancel', root_path, { class: "w-100 btn btn-lg" }) %>
  <% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='text-center'>
    <%= yield %>
  </body>
</html>

app/views/transfers/new.html.erb
<style>
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
</style>

<main class="form-signin">
  <% flash.each do |type, msg| %>
  <div class="alert alert-primary" role="alert">
      <%= msg %>
  </div>
  <% end %>
  <% @tf.errors.full_messages.each do |x| %>
  <div class="alert alert-secondary" role="alert">
    <%= x %>
  </div>
  <% end %>
  <%= form_with model: @tf do |form| %>
    <h1 class="h3 mb-3 fw-normal">Transfer</h1>
    </br>
    <h2>From Wallet: <%= @source_wallet&.name %></h2>
    </br>
    <h3>Balance: <%= @source_wallet&.total %></h3>

    <div class="form-floating">
      <%= form.select(:target_id, options_for_select(@wallets.map{|x| [x.name, x.id]}, 2), {}, { class: 'form-control' }) %>
      <%= form.label(:target_id, "To wallet :") %>
    </div>
    <div class="form-floating">
      <%= form.hidden_field(:user_id) %>
      <%= form.hidden_field(:source_id, { value: @tf.source&.id || params[:source_id] }) %>
      <%= form.text_field(:total, { class: 'form-control', value: @tf.total || '10.0'}) %>
      <%= form.label(:total, "Total :") %>
    </div>

    </br>
    <%= submit_tag('Transfer', { class: "w-100 btn btn-lg btn-primary" }) %>
    <%= link_to('Cancel', root_path, { class: "w-100 btn btn-lg" }) %>
  <% end %>
</main>

app/views/users/index.html.erb
<div style="margin-left: 10%;">
  <% flash.each do |type, msg| %>
  <div class="alert alert-primary" role="alert">
    <%= msg %>
  </div>
  <% end %>
  <table cellpadding="" cellspacing="0" border="0" class="table table-striped" style="border-collapse: unset">
    <thead>
      <tr>
        <th>User Name</th>
        <th>Email</th>
        <th>Wallet name</th>
        <th>Total</th>
        <th>Transaction</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td class="center"><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.wallet&.name %></td>
        <td><%= user.wallet&.total %></td>
        <td>
          <%= link_to 'Deposit', new_deposit_path({ target_id: user.wallet&.id }) %> | <%= link_to 'Withdraw', new_withdraw_path({ source_id: user.wallet&.id }) %> | <%= link_to 'Transfer', new_transfer_path(source_id: user.wallet&.id) %>

        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/withdraws/new.html.erb
<style>
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
</style>

<main class="form-signin">
  <% flash.each do |type, msg| %>
  <div class="alert alert-primary" role="alert">
      <%= msg %>
  </div>
  <% end %>
  <% @wd.errors.full_messages.each do |x| %>
  <div class="alert alert-secondary" role="alert">
    <%= x %>
  </div>
  <% end %>
  <%= form_with model: @wd do |form| %>
    <h1 class="h3 mb-3 fw-normal">Withdraw</h1>
    </br>
    <h2>Send to Wallet: <%= @source_wallet&.name %></h2>
  
    <div class="form-floating">
      <%= form.hidden_field(:user_id) %>
      <%= form.hidden_field(:source_id, { value: @wd.source&.id || params[:source_id] }) %>
      <%= form.text_field(:total, { class: 'form-control', value: @wd.total || '10.0'}) %>
      <%= form.label(:total, "Total :") %>
    </div>

    </br>
    <%= submit_tag('Withdraw', { class: "w-100 btn btn-lg btn-primary" }) %>
    <%= link_to('Cancel', root_path, { class: "w-100 btn btn-lg" }) %>
  <% end %>
</main>